extends SceneTree
## Dumps data/host/host_catalog.tres to a recording checklist for external VO talent.
##
## The lead time on Host VO is coordinating people to record, not writing code, so
## this exists to get a checklist out the door early rather than to be clever. See
## docs/Mayhem/11 Asset Pipeline.md and the backlog plan, tanda A2.
##
##     godot --headless --path . -s tools/export_host_script.gd
##
## Writes docs/host_script/host_script.csv (paste into a spreadsheet) and
## docs/host_script/host_script.md (a readable checklist), grouped by occasion.
## Deterministic: re-running with an unchanged catalog produces byte-identical output.
##
## line_id convention (also the expected recording filename, "<line_id>.ogg", per
## NarratorManager/HostPresenter's res://assets/audio/voice/<presenter_id>/<line_id>.ogg
## layout): "<set_id>_<01-based index, zero-padded to 2 digits>", e.g. "first_blood_01".
## This id has to stay stable - if a set's lines get reordered or one gets inserted
## in the middle, every already-recorded file after it silently points at the wrong
## line. Append new lines to the end of a set, never insert.

const CATALOG_PATH: String = "res://data/host/host_catalog.tres"
const CSV_OUTPUT_PATH: String = "res://docs/host_script/host_script.csv"
const MD_OUTPUT_PATH: String = "res://docs/host_script/host_script.md"

## Mirrors NarratorManager.Tier / .Priority by value, deliberately not by reference.
## A static type reference to HostCatalog/HostLineSet/NarratorManager anywhere in
## this file forces the GDScript compiler to fully resolve that class - and
## NarratorManager.gd itself references EventBus, an autoload - as part of
## compiling *this* script, which happens before autoloads exist and fails with
## "Identifier not found: EventBus". Every load() below is deliberately untyped and
## every field access is dynamic (duck-typed) to avoid triggering that eager
## resolution. Keep these two arrays in sync with narrator_manager.gd by hand.
const TIER_NAMES: PackedStringArray = ["", "STANDARD", "WARNING", "PUNCHLINE"]
const PRIORITY_NAMES: PackedStringArray = ["FLAVOR", "FEEDBACK", "STATE", "CRITICAL"]

const MD_HEADER: String = """---
tags: [mayhem, audio, host, recording]
---

# MAYHEM — Host VO recording script

Generated by `tools/export_host_script.gd` from `data/host/host_catalog.tres`.
Re-run the tool after editing the catalog; do not hand-edit this file.

**Format:** deliver each line as a mono `.ogg`, named exactly as shown (case-sensitive),
in a folder we'll tell you separately. **Deliver `PUNCHLINE` lines with extra emphasis** —
in game they get the full-screen treatment instead of a subtitle rail, so a flat read
undersells them. `WARNING` lines carry a threat the player has to react to; read them
with urgency, not humor. Everything else (`STANDARD`) is dry stadium-announcer sarcasm —
think a boxing ring announcer who has seen this exact fight a thousand times.

**Do not reorder or skip lines within an occasion.** The filename is tied to line
order; an out-of-order recording silently plays the wrong line in game.

"""


func _initialize() -> void:
	if not ResourceLoader.exists(CATALOG_PATH):
		push_error("export_host_script: no catalog at %s" % CATALOG_PATH)
		quit(1)
		return

	var catalog: Resource = load(CATALOG_PATH)
	var sets: Array = catalog.get("sets") if catalog != null else []
	if catalog == null or sets.is_empty():
		push_error("export_host_script: catalog at %s is empty" % CATALOG_PATH)
		quit(1)
		return

	var rows: Array[Dictionary] = _build_rows(sets)
	if not _has_unique_ids(rows):
		quit(1)
		return

	DirAccess.make_dir_recursive_absolute(MD_OUTPUT_PATH.get_base_dir())
	_write_csv(rows)
	_write_markdown(rows)
	print("Exported %d lines across %d occasions to %s" % [
		rows.size(), sets.size(), MD_OUTPUT_PATH.get_base_dir()])
	quit()


func _build_rows(sets: Array) -> Array[Dictionary]:
	var rows: Array[Dictionary] = []
	for line_set: Variant in sets:
		if line_set == null:
			continue
		var lines: Array = line_set.get("lines")
		if lines.is_empty():
			continue
		var set_id: String = String(line_set.get("id"))
		var tier: int = int(line_set.get("tier"))
		var priority: int = int(line_set.get("priority"))
		var tier_name: String = TIER_NAMES[tier] if tier < TIER_NAMES.size() else "?"
		var priority_name: String = (
			PRIORITY_NAMES[priority] if priority < PRIORITY_NAMES.size() else "?")
		for i: int in lines.size():
			var line_id: String = "%s_%02d" % [set_id, i + 1]
			rows.push_back({
				"set_id": set_id,
				"line_id": line_id,
				"filename": "%s.ogg" % line_id,
				"tier": tier_name,
				"priority": priority_name,
				"text": String(lines[i]),
			})
	return rows


## `line_id` is the recording filename - a collision means two lines would overwrite
## each other on disk, so this is a hard stop, not a warning.
func _has_unique_ids(rows: Array[Dictionary]) -> bool:
	var seen: Dictionary = {}
	var ok: bool = true
	for row: Dictionary in rows:
		var id: String = row["line_id"]
		if seen.has(id):
			push_error("export_host_script: duplicate line_id '%s'" % id)
			ok = false
		seen[id] = true
	return ok


func _write_csv(rows: Array[Dictionary]) -> void:
	var file: FileAccess = FileAccess.open(CSV_OUTPUT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("export_host_script: cannot write %s" % CSV_OUTPUT_PATH)
		quit(1)
		return
	file.store_line("occasion,line_id,filename,tier,priority,text")
	for row: Dictionary in rows:
		file.store_line(",".join([
			_csv_field(row["set_id"]), _csv_field(row["line_id"]),
			_csv_field(row["filename"]), _csv_field(row["tier"]),
			_csv_field(row["priority"]), _csv_field(row["text"]),
		]))


func _csv_field(value: String) -> String:
	if value.find(",") >= 0 or value.find("\"") >= 0 or value.find("\n") >= 0:
		return "\"%s\"" % value.replace("\"", "\"\"")
	return value


func _write_markdown(rows: Array[Dictionary]) -> void:
	var file: FileAccess = FileAccess.open(MD_OUTPUT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("export_host_script: cannot write %s" % MD_OUTPUT_PATH)
		quit(1)
		return

	file.store_string(MD_HEADER)

	var current_set: String = ""
	for row: Dictionary in rows:
		if row["set_id"] != current_set:
			current_set = row["set_id"]
			file.store_line("## %s\n" % current_set)
		file.store_line("- [ ] `%s` (%s / %s) — %s" % [
			row["filename"], row["tier"], row["priority"], row["text"]])
		file.store_line("")
